
services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - qdrant
      - redis
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./prompts:/app/prompts

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    ports:
      - "8001:8001"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - qdrant
      - redis

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - GATEWAY_URL=http://gateway:8000
    env_file:
      - .env
    depends_on:
      - gateway

volumes:
  qdrant_storage:
  redis_data: